FROM confluentinc/cp-kafka-connect:7.5.0

USER root
RUN yum update -y && yum install -y gettext && yum clean all

# 엔트리포인트 복사 및 실행 권한 부여
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh \
    && chown appuser:appuser /entrypoint.sh

USER appuser

ENV CLASSPATH=/usr/share/java/kafka-connect-jdbc/*

ENTRYPOINT ["/entrypoint.sh"]